### ISSUE TITLE
Incorrect Paths in updated  dapp-launchpad.config.json after init

### ISSUE THREAD

**Issue by ankitmawle** [0xPolygon/dapp-launchpad#18]
After we initialize a new project using `dapp-launchpad init [project name] `  all paths mentioned in generated dapp-launchpad.config.json are incorrect and miss the project name

This generates following error  
![error](https://github.com/0xPolygon/dapp-launchpad/assets/35817253/0d239c34-4651-4490-b9ff-e210bc4b9d09)

This is my generated dapp-launchpad.config.json
![config](https://github.com/0xPolygon/dapp-launchpad/assets/35817253/f0de05aa-04c4-4dc0-9cce-fbb8aa0db399)

**Comment by ankitboghra** [comment]
Issue fixed #17
